liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "images/cache"
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public/"

    driver:               "gd"
    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction
#
#    # define your filter sets under this option
    filter_sets:
#
#        # an example thumbnail transformation definition
#        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        cat_thumb:
#
#            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
#
#            # setup the filter steps to apply for this transformation
            filters:
#
#                # auto rotate the image using EXIF metadata
                auto_rotate: ~
#
#                # strip the image of all metadata
                strip: ~
#
#                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [400, 450]
                    mode:          outbound
#                    allow_upscale: true
#
#                # create border by placing image on larger black background
                background:
                    size:     [400, 450]
                    position: center
                    color:    '#F2F2F2'

        art_thumb:
#
#            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
#
#            # setup the filter steps to apply for this transformation
            filters:
#
#                # auto rotate the image using EXIF metadata
                auto_rotate: ~
#
#                # strip the image of all metadata
                strip: ~
#
#                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [1000, 500]
                    mode:          outbound
#                    allow_upscale: true
#
#                # create border by placing image on larger black background
                background:
                    size:     [1000, 500]
                    position: center
                    color:    '#F2F2F2'

        mini_thumb:
#
#            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8
#
#            # setup the filter steps to apply for this transformation
            filters:
#
#                # auto rotate the image using EXIF metadata
                auto_rotate: ~
#
#                # strip the image of all metadata
                strip: ~
#
#                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [150, 150]
                    mode:          outbound
#                    allow_upscale: true
#
#                # create border by placing image on larger black background
                background:
                    size:     [150, 150]
                    position: center
                    color:    '#F2F2F2'
