swiftmailer:
    # transport: "%mailer_transport%"
    # host: "%mailer_host%"
    # username: "%mailer_username%"
    # password: "%mailer_password%"
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
